tarea_2/seia/urls.py
from django.urls import path
from . import views

app_name = "projects"


urlpatterns = [
    path('api/', views.load_data, name="api"),
    path('json/', views.get_json, name="json"),
    path('', views.ProyectListView.as_view(), name="list"),
]

tarea_2/tarea_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seia.urls'))
]

tarea_2/seia/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    nombre = models.CharField(max_length=255)
    tipo = models.CharField(max_length=255)
    region = models.CharField(max_length=255)
    tipologia = models.CharField(max_length=255)
    titular = models.CharField(max_length=255)
    inversion = models.CharField(max_length=255)
    fecha = models.CharField(max_length=255)
    estado = models.CharField(max_length=255, null=True)

    class META:
        verbose_name = "Proyecto"
        verbose_name = "Proyectos"

    def __str__(self):
        return self.nombre
    

tarea_2/seia/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.core import serializers

from selenium.webdriver.chrome.options import Options 
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

from selenium import webdriver

from .models import Project

import time

# Create your views here.

def get_url(page_number):
    variable_url = f"https://seia.sea.gob.cl/busqueda/buscarProyectoAction.php?nombre=&_paginador_refresh=1&_paginador_fila_actual={page_number}"
    return variable_url

def create_dict(headers):
        dict_data = {}
        for key in headers:
            dict_data[key] = ""
        return dict_data

def create_dict_data(data, headers):
        list_dict = []
        dict_data = create_dict(headers)

        for row in data:
            count_row = 0
            dict_data = create_dict(headers)
            for value in row:
                dict_data[headers[count_row]] = value
                count_row += 1
            list_dict.append(dict_data)

        return list_dict

def get_list_data(driver, total_pages):
    
        lista_datos = []
        lista = []
        
        for page in range(total_pages+1):

            try:
        
                driver.get(get_url(page))
            
            except NoSuchElementException:
                time.sleep(2)
            
            table = driver.find_elements("xpath",".//*[@class='tabla_datos']/tbody/tr")
            
            for row in table:
                lista = []
                for i in row.find_elements(By.TAG_NAME,"td"):
                    lista.append(i.text)
                lista_datos.append(lista)
                
        return lista_datos

def load_data(request):

    url = "https://seia.sea.gob.cl/busqueda/buscarProyectoAction.php"

    options = webdriver.ChromeOptions()
    

    chrome_options = Options()
    chrome_options.add_argument("--disable-extensions")
    chrome_options.add_argument("--disable-gpu")

    driver = webdriver.Chrome(options=chrome_options)

    driver.get(url)

    headers = driver.find_elements("xpath","//*[@class='tabla_datos']/thead/tr/th")
    list_headers = [row.text for row in headers]
    total_pages = int(driver.find_elements("xpath",".//select[@name='pagina_offset']")[-1].text.split("\n")[-1])

    
    proyects = create_dict_data(get_list_data(driver, total_pages), list_headers)

    

    for proyect in proyects:
        Project.objects.create(
            id=proyect[list_headers[0]],
            nombre=proyect[list_headers[1]],
            tipo=proyect[list_headers[2]],
            region=proyect[list_headers[3]],
            tipologia=proyect[list_headers[4]],
            titular=proyect[list_headers[5]],
            inversion=proyect[list_headers[6]],
            fecha=proyect[list_headers[7]],
            estado=proyect[list_headers[8]]
        )

    driver.close()

    return HttpResponseRedirect(reverse_lazy('projects:list'))


def get_json(request):
    projects = Project.objects.all()
    projects_list = serializers.serialize('json', projects)
    return HttpResponse(projects_list, content_type="text/json-comment-filtered")


class ProyectListView(ListView):
    model = Project
    template_name = "project/projects_list.html"
    

tarea_2/seia/templates/project/projects_list.html
{% extends 'base.html' %}


{% block content %}

    

    <div class="container">

        <h1 class="mt-4">Proyectos SEIA</h1>

        <div class="container">
            <div class="row">
                <form action="" method="get">
                    
                    <div class="btn-group col 4">
                        <a class="btn btn-success col" href="{% url 'projects:api' %}">Actualizar Lista</a>
                        <a class="btn btn-warning col" href="{% url 'projects:json' %}">Obtener Json</a>
                    </div>
                </form>
                
                
            </div>
            
        </div>

        <div class="container">

            <table class="table table-striped mt-4">
                <thead class="table-dark">
                    <tr>
                        <th>Nº</th>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Region</th>
                        <th>Tipología</th>
                        <th>Titular</th>
                        <th>Inversión</th>
                        <th>Fecha</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in object_list %}
                    
                    <tr>
                        <td>{{project.id}}</td>
                        <td>{{project.nombre}}</td>
                        <td>{{project.tipo}}</td>
                        <td>{{project.region}}</td>
                        <td>{{project.tipologia}}</td>
                        <td>{{project.titular}}</td>
                        <td>{{project.inversion}}</td>
                        <td>{{project.fecha}}</td>
                        <td>{{project.estado}}</td>
                        
                    </tr>
                    
                    {% endfor %}
                </tbody>
    
            </table>
    

        </div>
    
    </div>


    
    
    {% endblock content %}

tarea_2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Información de Estaciones de Bicicletas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        {% block content %}
    
        {% endblock content %}
    </div>
    


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    
</body>




</html>