tarea_1/bike/urls.py
from django.urls import path
from . import views

app_name = "bike"

urlpatterns = [
    path('api/', views.api_bikes, name="bikes_api"),
    path('', views.StationsListView.as_view(), name="list"),
    path('detail/<pk>/', views.StationsDetailView.as_view(), name="detail")
]

tarea_1/tarea_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('bike.urls'))
]

tarea_1/bike/models.py
from django.db import models
import uuid
from multiselectfield import MultiSelectField

# Create your models here.


class Station(models.Model):

    '''
    Modelo Stations en donde se almacena la información de la API
    '''

    PAYMENT_CHOICES = [
        ('key', 'Tarjeta'),
        ('transitcard', 'Tarjeta de Transito'),
        ('creditcard', 'Tarjeta de Crédito'),
        ('phone', 'Teléfono Movil')
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    empty_slots = models.IntegerField("Slots")
    #extra
    free_bikes = models.IntegerField("Free Bikes", null=True, blank=True)
    latitude = models.FloatField("Latitude", null=True, blank=True)
    longitude = models.FloatField("Longitude", null=True, blank=True)
    name = models.CharField("Name", max_length=255, null=True, blank=True)
    timestamp = models.CharField(null=True, blank=True, max_length=200)
    address = models.CharField("address", max_length=255, null=True, blank=True)
    altitude = models.FloatField(null=True, blank=True)
    ebikes = models.IntegerField(null=True, blank=True)
    has_ebikes = models.BooleanField(null=True, blank=True)
    last_updated = models.CharField(null=True, blank=True, max_length=200)
    normal_bikes = models.IntegerField(null=True, blank=True)
    payment =  MultiSelectField(choices=PAYMENT_CHOICES, null=True, blank=True)
    post_code = models.CharField(null=True, max_length=100, default=None, blank=True)
    renting = models.IntegerField(null=True, blank=True)
    returning = models.IntegerField(null=True, blank=True)
    slots = models.IntegerField(null=True, blank=True)
    uid = models.IntegerField(null=True, blank=True)

    class META:
        verbose_name = "Estación"
        verbose_name = "Estaciones"


    def __str__(self):
        return self.name

    def get_url_map(self):
        from django.utils.html import format_html
        return format_html(f"http://maps.google.com/maps?z=12&t=m&q=loc:{self.latitude}+{self.longitude}")

tarea_1/bike/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from .models import Station

import requests

# Create your views here.


def api_bikes(request):

    response = requests.get("http://api.citybik.es/v2/networks/bikesantiago")
    data_bikes = response.json()

    #Aqui leo la información de la API desde el archivo creado
    
    # with open("/Users/abelaguilera/Desktop/postulacion_CHR/test-Abel-CHR/tarea_1/bikes_data.json") as file:
    #     data_bikes = json.load(file)

    for station in data_bikes['network']['stations']:

        print(station)

        if 'post_code' in station['extra'].keys():
            Station.objects.get_or_create(
                id = station["id"],
                empty_slots = station['empty_slots'],
                free_bikes = station['free_bikes'],
                latitude = station['latitude'],
                longitude = station['longitude'], 
                name = station['name'],
                timestamp = station['timestamp'],
                address = station['extra']['address'],
                altitude = station['extra']['altitude'],
                ebikes = station['extra']['ebikes'],
                has_ebikes = station['extra']['has_ebikes'],
                last_updated = station['extra']['last_updated'],
                normal_bikes = station['extra']['normal_bikes'],
                payment = station['extra']['payment'],
                post_code = station['extra']['post_code'],
                renting = station['extra']['renting'],
                returning = station['extra']['returning'],
                slots = station['extra']['slots'],
                uid = station['extra']['uid']
            )
        else:
            Station.objects.get_or_create(
                id = station["id"],
                empty_slots = station['empty_slots'],
                free_bikes = station['free_bikes'],
                latitude = station['latitude'],
                longitude = station['longitude'], 
                name = station['name'],
                timestamp = station['timestamp'],
                address = station['extra']['address'],
                altitude = station['extra']['altitude'],
                ebikes = station['extra']['ebikes'],
                has_ebikes = station['extra']['has_ebikes'],
                last_updated = station['extra']['last_updated'],
                normal_bikes = station['extra']['normal_bikes'],
                payment = station['extra']['payment'],
                renting = station['extra']['renting'],
                returning = station['extra']['returning'],
                slots = station['extra']['slots'],
                uid = station['extra']['uid']
            )
    



    return HttpResponseRedirect(reverse_lazy("bike:list"))


class StationsListView(ListView):
    model = Station
    paginate_by = 20
    

    def get_context_data(self, **kwargs):

        context = super(StationsListView, self).get_context_data(**kwargs)

        filter = self.request.GET.get("search_filter")

        if filter:
            context['object_list'] = self.model.objects.filter(
                name__contains=filter
            )
            
        else:
            context['object_list'] = self.model.objects.all()
        
        return context

    

class StationsDetailView(DetailView):
    model = Station

tarea_1/bike/templates/bike/station_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="container">

    <h1 class="mt-4 mb-3">Información de estación - {{ object.name }}</h1>

    <div class="row">
        <div class="col">
            <div class="card border-primary mb-3 col-6">

                <div class="card-header">General Information</div>
                <div class="card-body">


                    
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="form-label" for="disabledInput">Slots</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                    value="{{ object.empty_slots }}">
                            </fieldset>
                        


                        
                            <fieldset disabled="">
                                <label class="form-label" for="disabledInput">Free Bikes</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                    value="{{ object.free_bikes }}">
                            </fieldset>
                        


                        
                            <fieldset disabled="">
                                <label class="form-label" for="disabledInput">Latitude</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                    value="{{ object.latitude }}">
                            </fieldset>
                        


                        
                            <fieldset disabled="">
                                <label class="form-label" for="disabledInput">Longitude</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                    value="{{ object.longitude }}">
                            </fieldset>

                            <fieldset disabled="">
                                <label class="form-label" for="disabledInput">Free bikes</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                    value="{{ object.free_bikes }}">
                            </fieldset>
                            
                        </div>
                    
                </div>
            </div>
        </div>
    </div>

    <div class="col">

        <div class="card border-primary mb-3 col-6">
            <div class="card-header">Extra information</div>
            <div class="card-body">

                <div class="row">
                    <div class="form-group">
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Address</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.address }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Altitude</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.altitude }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Ebikes</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.ebikes }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Last Updated</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.last_updated }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Normal bikes</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.normal_bikes }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Payment</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.payment }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Payment Terminal</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.payment_terminal }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Post Code</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.post_code }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Renting</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.renting }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Returning</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.returning }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">Slots</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.slots }}">
                        </fieldset>
                        <fieldset disabled="">
                            <label class="form-label" for="disabledInput">UID</label>
                            <input class="form-control" id="disabledInput" type="text" placeholder="" disabled=""
                                value="{{ object.uid }}">
                        </fieldset>
                    </div>
                </div>

            </div>
        </div>

    </div>
            
    


    

        

    
</div>


{% endblock content %}

tarea_1/bike/templates/bike/station_list.html
{% extends 'base.html' %}


{% block content %}

    

    <div class="container">

        <h1 class="mt-4">Data base Bike Stations</h1>

        <div class="container">
            <div class="row">
                <form action="" method="get">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Buscar nombre de estación" name="search_filter">
                        <button class="btn btn-primary" type="submit" id="button-addon2">Buscar</button>
                      </div>
                    <div class="btn-group col 4">
                        <a class="btn btn-success col-3" href="{% url 'bike:bikes_api' %}">Actualizar Lista</a>
                    </div>
                </form>
                
                
            </div>
            
        </div>

        <div class="container">

            <table class="table table-striped mt-4">
                <thead class="table-dark">
                    <tr>
                        <th>Name</th>
                        <th>Slots</th>
                        <th>Free Bikes</th>
                        <th>Ubication</th>
                    </tr>
                </thead>
                <tbody>
                    {% for station in object_list %}
                    
                    <tr>
                        <td><a href="{% url 'bike:detail' station.id %}">{{station.name}}</a></td>
                        <td>{{station.empty_slots}}</td>
                        <td>{{station.free_bikes}}</td>
                        <td><a href="{{station.get_url_map}}" target=”_blank”>Aqui</a></td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
    
            </table>
    

        </div>
    
    </div>


    
    
    {% endblock content %}

tarea_1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Información de Estaciones de Bicicletas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        {% block content %}
    
        {% endblock content %}
    </div>
    


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    
</body>




</html>